{
 "title": "OSM Stats New",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Orders Received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "osm_orders_today" }
   ]
  },
  {
   "title": "Orders Delivered",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "osm_comp_orders_today" }
   ]
  },
  {
   "title": "Fulfilment Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(osm_comp_orders_today/osm_orders_today)*100"
    }
   ]
  },
  {
   "title": "SLA Breached",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "osm_sla_breach" }
   ]
  },
  {
   "title": "Orders in Jeopardy",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "osm_orders_jeopardy" }
   ]
  },
  {
   "title": "Order Trends",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "osm_orders_metric_today" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "content": "<img src=https://nltd.s3.amazonaws.com/NLT_SG_Map.png>\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "SOM Order Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "expr": "osm_orders_lifetime{role='som'}"
    }
   ]
  },
  {
   "title": "TOM Order Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "format": "m",
   "valueName": "avg",
   "targets": [
    {
     "expr": "osm_orders_lifetime{role='tom'}"
    }
   ]
  }
 ]
}